services:
  frontend-app:
    build:
      context: ./student-club-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    container_name: studentclub-frontend
    ports:
      - "3000:3000"

  backend-app:
    build:
      context: ./student-club-backend
      dockerfile: Dockerfile
    container_name: studentclub-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/student-club-management-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      JWT_SECRET: f97e0211f5639eb97d55a439adc981b4b48584e9cff069501fdb1dbaa334af5ddef03464716648b7273d86d0b0970a315e1b0975a154466be04343bedacf3135
      JWT_EXPIRATION: 3600000

      FRONTEND_URL: http://localhost:3000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: studentclub-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: student-club-management-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
