services:
  frontend-app:
    build:
      context: ./student-club-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    container_name: studentclub-frontend
    ports:
      - "3000:3000"

  backend-app:
    build:
      context: ./student-club-backend
      dockerfile: Dockerfile
    container_name: studentclub-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 3600000

      FRONTEND_URL: http://localhost:3000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: studentclub-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: student-club-management-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
